### ISSUE TITLE
Images in notification emails are not linked to their source in ascii-collab

### ISSUE THREAD

**Issue by thunderrabbit** [MartinSStewart/ascii-collab#2]
As of August 1st JST [1], images in ascii-collab emails have been sent as attachments.

When I click the images now, I see the image in my email app.  The email still says "Click on an image to view it in ascii-collab" but that is not working.

[1] The email that says Generated at 1659363794702 was the first with this issue.

**Comment by MartinSStewart** [comment]
I haven't made any changes to how the emails are generated. Maybe something has changed in your email client, can you check if older emails now also have this problem?

**Comment by thunderrabbit** [comment]
It wasn't the client, but one of my mail servers (anonaddy) started treating attachments differently.   I used a new address that skips that server and images are showing up inline again.
